services:
  # Backend Service
  - type: web
    name: gymbro-backend
    env: python
    rootCommand: cd server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: gymbro-frontend
    env: node
    rootCommand: cd client
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 4173 --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: gymbro-backend
          property: host
